### ISSUE TITLE
Task payment and ownership stake in the Colony

### ISSUE THREAD

**Issue by iainbarclay** [farahbrunache/travay-colony-vuejs-dapp#9]
One thing that stood out when reading the WP is that you can pay in a mix of currencies - so for example, you could pay 80 or 90% in ETH (or DAI if you want a US$ linked currency) but you can also pay some in the TRAVAY token - which would effectively give workers an ownership of the some tiny part of the Colony and an incentive to help make the Colony bigger - and raise more funds - eg. you could do a reward share payment to the token owners a few times a year, and the people who had done the most (good) work would get paid this proportionally.

Probably too much for MVP, but worth thinking for future - ownership and ongoing engagement to make the Colony bigger and better would seem to be a good thing.

**Comment by farahbrunache** [comment]
Closing, moving to our kanban board.
